console_windows.go

Signed-off-by: Kenfe-Mickael Laventure <mickael.laventure@gmail.com>

Use proper fd when retrieving console size on windows

---

tc_darwin.go
tc_freebsd.go

I had assumed that tc was the same in FreeBSD and Darwin but of
course not exactly.
Signed-off-by: Justin Cormack <justin.cormack@docker.com>

Fixes for FreeBSD

---

console.go
console_test.go

This needs to be reordered with Height first then Width to match struct
winsize.
Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

Fix WinSize struct W/H

---

console_unix.go
tc_darwin.go
tc_freebsd.go
tc_linux.go

Define `tcmakeraw` directly in Go instead of using C. Allows for easier
cross compile.
Signed-off-by: Justin Cormack <justin.cormack@docker.com>
With this you can mostly cross compile `containerd` for Darwin on Linux (one more fix needed) as the cgo code removed. See https://github.com/containerd/containerd/issues/866

Remove use of cgo

---

console_linux.go

Fix the following warning issued by 'go vet' by adding a blank line
after the build clause:
console_linux.go:1: +build comment must appear before package clause and be followed by a blank line
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>

Fix go vet warning

---

.travis.yml
console_linux_test.go
console_unix.go
tc_darwin.go
tc_freebsd.go
tc_linux.go
tc_solaris_cgo.go
tc_solaris_nocgo.go
tc_unix.go

since the last moby summit i've been working on porting containerd to
solaris.  to do this i need to make changes to this vendored component.
at the summit i was asked to try and err on the side of having multiple
smaller changesets rather than one large changeset.  to that end, this
pull request contains the smallest amount of changes necessary to get
this component to compile on solaris, to cross-compile for solaris on
linux, and to test solaris cross-compilation on linux via travis ci.
it's worth mentioning that while these these changes allow solaris
cross-compilation on linux, the resultant binary isn't actually usable
on solaris.  this is because compilation of this component on solaris
requires the use of cgo, and we can't cross-compile solaris cgo code on
linux.  I chose to enable …

Add solaris build support

---

tc_darwin.go
tc_freebsd.go
tc_linux.go
tc_solaris_cgo.go
tc_solaris_nocgo.go
tc_unix.go

The functions IoctlGetTermios/IoctlSetTermios and
IoctlGetWinsize/IoctlSetWinsize were recently added to package
golang.org/x/sys/unix for Darwin and FreeBSD. This allows to reduce code
duplication and combine the implementations for tcget, tcset, tcgwinsz,
tcswinsz, saneTerminal and cfmakeraw for Darwin, FreeBSD, Linux and
Solaris.
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>

Use common tc* functions on FreeBSD and Darwin

---

.travis.yml
tc_linux.go

On big-endian architectures unix.IoctlGetInt() leads to a wrong result
because a 32 bit value is stored into a 64 bit buffer. When dereferencing
the result is left shifted by 32. Without this patch ptsname() returns
a wrong path from the second pty onwards.
To protect syscalls against re-arranging by the GC the conversion from
unsafe.Pointer to uintptr must occur in the Syscall expression itself.
See the documentation of the unsafe package for details.
Signed-off-by: Peter Morjan <peter.morjan@de.ibm.com>

Fix ptsname() for big-endian architectures

---

.travis.yml
console_unix.go
tc_openbsd_cgo.go
tc_openbsd_nocgo.go
tc_unix.go

As neither `TIOCGPTN` nor `TIOCPTYGNAME` syscalls are supported on OpenBSD there is the same story as it is with Solaris - we have to use libc funcions.

Add OpenBSD support

---

console_linux.go

Possible race:
```
Thread1:			Thread2:
line 178: Read() -> EAGAIN	...
<reschedule>			line 110: EpollWait()
...				line 124: signalRead()
...				...
line 191: Wait()		...
line 110: EpollWait()
```
Thread2 (epoll) sends signalRead() (via sync.Cond) but Thread1 is not waiting
yet. Then is start to wait, but no more signals will arrive (because Thread2
is sleeping in EpollWait() on edge-triggered epoll.
To prevent this race one should held Lock when sending signalRead().
The same situation goes with Write loop.
Bug was reported to docker: https://github.com/docker/for-linux/issues/353
Signed-off-by: Alexander Gerasiov <gerasiov@yandex-team.ru>

console_linux: Fix race: lock Cond before Signal.

---

.travis.yml
LICENSE
README.md

Signed-off-by: Phil Estes <estesp@linux.vnet.ibm.com>

Add common project repo checks/README references

---

console.go
console_unix.go
console_windows.go

The reason of the introduction of the interface is due to the need to pass another thing than a os.File.
In my use case, the problem is that calling `os.Newfile` invalidates the file descriptor after a variable gets out of the scope of a function since `os.File` has a `finalizer`. This forces me to make a global variable to hold it and avoid the GC. Check https://github.com/docker/app/commit/d26c9ad7f5a20a161e9d5d7df7d46c06c69ac565
By accepting an interface (still compatible with `os.File`), another structure can be passed. Like in:
https://github.com/ulyssessouza/buildx/commit/5941345e21ebda43723a475380135fe3741d6b3c
With this approach, a new struct can be passed, like in: https://github.com/docker/app/pull/779/commits/341121245d3217ecb1eeb15b11d52d7d1986adf0#diff-03504424ddde121c663ff197 …

Add File interface instead of using os.File

---

console_linux.go
console_linux_test.go

Previously, multiple calls to epoller.Close() could result in unix.Close being
called on the same FD value multiple times. This made it easy for consumers to
create race conditions where calls to Close after the first one were closing
unrelated FDs in the process that happened to use the same value of the epoller
FD.
This change uses sync.Once to ensure that unix.Close is only called once, with
subsequent calls to Close returning "file already closed" instead.
Signed-off-by: Erik Sipsma <erik@sipsma.dev>
See these issues for more background on when this was originally noticed/debugged:
* https://github.com/containerd/containerd/issues/3895
* https://github.com/firecracker-microvm/firecracker-containerd/issues/363

Only close epoller FD at most once.

---

.travis.yml
console.go

In case we have stdin redirected, we still have a terminal which
can be obtained from stdout or stderr. This is what this commit
does.
This should allow something like this to work:
> ctr run --rm --tty docker.io/library/hello-world:latest xxx < /dev/null
_(found while working on https://github.com/opencontainers/runc/issues/2485)_
NB: in case all three are redirected, but we still have a controlling
tty, we can easily get it by opening /dev/tty, but then it should be
closed, and it's not quite clear by whom and when, so this is left as
a home exersize for the reader.

Current: allow stdin to be redirected

---

.github/workflows/ci.yml
.golangci.yml
console.go

Also add linting to CI and remove travis script entries that were no-ops
(there are no tests for other platforms so the extra `go test`
invocations with GOOS settings were not doing anything)
Signed-off-by: Phil Estes <estesp@linux.vnet.ibm.com>

Enable Github Actions-based CI

---

.github/workflows/ci.yml

Getting the golangci-lint package needs to be done with the gomod
method.
I promise I tested it this time @thaJeztah! It is working on my fork. 😅 
Signed-off-by: Phil Estes <estesp@linux.vnet.ibm.com>

Fix actions to follow the model from other repos

---

tc_linux.go

Use `unix.IoctlSetPointerInt` and `unix.IoctlGetInt` instead of manually
implementing them. This avoid the use of the `unsafe` package.

Use Ioctl{SetPointerInt,GetInt} from golang.org/x/sys/unix on linux

---

.github/workflows/ci.yml
README.md

- GHA: update to Go 1.16.x, actions/setup-go@v2
- README: update badges to show GHA status
This was overlooked when switching to GHA. Also adds badges for go.pkg.dev and Go Report Card.

GHA: update to Go 1.16.x, actions/setup-go@v2, fix badges

---

tc_linux.go

This reverts commit f1b333f2c5050f (Use Ioctl{SetPointerInt,GetInt} from
golang.org/x/sys/unix on linux), changing the code to what it was after
commit dbd69c59b81. This fixes a blocker bug on s390 [1].
The original description from commit dbd69c59b81 follows:
On big-endian architectures unix.IoctlGetInt() leads to a wrong result
because a 32 bit value is stored into a 64 bit buffer. When dereferencing
the result is left shifted by 32. Without this patch ptsname() returns
a wrong path from the second pty onwards.
To protect syscalls against re-arranging by the GC the conversion from
unsafe.Pointer to uintptr must occur in the Syscall expression itself.
See the documentation of the unsafe package for details.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1941815
This is a regression in …

Fix ptsname() for big-endian architectures (again)

---

console_test.go
console_unix.go
pty_freebsd_cgo.go
pty_freebsd_nocgo.go
pty_unix.go
tc_freebsd_cgo.go
tc_freebsd_nocgo.go

FreeBSD does not have a `/dev/ptmx` device unless the [`pty(4)` kernel driver](https://www.freebsd.org/cgi/man.cgi?query=pty&sektion=4) is loaded.  When that module is not loaded, pty devices can be allocated with [`posix_openpt(2)`](https://www.freebsd.org/cgi/man.cgi?query=posix_openpt&sektion=2&apropos=0&manpath=FreeBSD+12.2-RELEASE+and+Ports) instead.

add cgo-based FreeBSD support

---

pty_freebsd_nocgo.go

```
$ GOOS=freebsd CGO_ENABLED=0 go build .
./pty_freebsd_nocgo.go:30:17: undefined: os
```

Add missing import in freebsd nocgo stub

---

console_test.go
console_zos.go
tc_unix.go
tc_zos.go

Support for z/OS is requested as part of the effort by IBM to deliver a container runtime for z/OS.
The changes enable building for zos and should not impact other platforms. Having said that, the console test file was changed to allow the test to run reliably on z/OS. Although the change to the TestConsole implementation impacts linux and solaris as well, there is no intention to change the coverage of the test.
I ran the changed console test successfully with both zos and linux.

Add support for z/OS

---

console_windows.go
go.mod
go.sum

.. in favor of Go native error wrapping (available since Go 1.13).
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>

Stop using pkg/errors

---

console_windows.go

When resetting the Windows console modes, we must not abort on the first encountered error, otherwise we might leave the console in an unexpected state.
This is easily reproducible by calling SetRaw while stdout is redirected: Reset will abort restoring console modes after failing to reset stdout, which leaves stderr in its raw state.

fix: don't abort on first encountered error when resetting Windows console

---

console_windows.go

When stdin/err/out are redirected, console mode can't be changed. That's often expected & acceptable however, so we shouldn't print errors to stdout.

fix: don't print to stdout when initializing console fails on Windows

---

README.md

Since default branch of repo [github.com/containerd/project](https://github.com/containerd/project) changed to main, update the document links accordingly.
Signed-off-by: Tony Fang [nhfang@amazon.com](mailto:nhfang@amazon.com)

[Doc]update links to main

---

console.go
console_other.go
console_windows.go

Fixes build with:
env GOOS=js GOARCH=wasm go build -trimpath .

fix: add shim for js

---

tc_unix.go

According to `termios(3)`, `cfmakeraw` should perform `or` on `c_cflag` with `CS8`.
But the current our `cfmakeraw` implementation doesn't do that but clears that bit.
This commit fixes `cfmakeraw` to make it behave same as Linux's one.
https://man7.org/linux/man-pages/man3/termios.3.html
```
termios_p->c_iflag &= ~(IGNBRK | BRKINT | PARMRK | ISTRIP
| INLCR | IGNCR | ICRNL | IXON);
termios_p->c_oflag &= ~OPOST;
termios_p->c_lflag &= ~(ECHO | ECHONL | ICANON | ISIG | IEXTEN);
termios_p->c_cflag &= ~(CSIZE | PARENB);
termios_p->c_cflag |= CS8;
```

tc_unix.go: Make cfmakeraw compatible to Linux

---

.github/workflows/ci.yml
console_test.go
console_unix.go
tc_darwin.go
tc_freebsd_cgo.go
tc_freebsd_nocgo.go
tc_linux.go
tc_netbsd.go
tc_openbsd_cgo.go
tc_openbsd_nocgo.go
tc_zos.go

Security-conscious callers may wish to have more control over opening
/dev/ptmx, and so GetPty is not suitable for them. Previously it was not
possible for such users to open /dev/ptmx and then use this package to
create new ptys and manage the console.
On Linux, the intended usage would be for a daemon to get an O_PATH
handle to /dev/ptmx that can then be re-opened (through procfs) to get a
new handle to /dev/ptmx. I suspect on FreeBSD you could use O_EMPTY_PATH
to accomplish something similar.
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

pty: add GetPtyFromFile as safer GetPty
